export const catalog = [
  {
    artno: "Dm7582-100",
    model: "Blazer Low '77 Premium",
    brand: "Nike",
    price: 99,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: ["Coconut milk", "Forest green", "Beige"],
    sex: "Men",
    imgURL: "https://www.sneakersnstuff.com/images/314995/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/314994/dm7582-100-2.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/314996/dm7582-100-1.jpg",
    instock: true,
    description: "After seeing the original colorways of the classic Nike Blazer return it’s time to bring back the low-tops. Constructed with a white leather upper with black and grey suede overlays, these retro kicks are more than just a throwback for old heads, this breaths sneaker culture."
  },
  {
    artno: "Da8291-001",
    model: "Wmns Waffle Trainer 2",
    brand: "Nike",
    price: 89,
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    colors: ["Light Bone", "Beige", "Green"],
    sex: "Woman",
    imgURL: "https://www.sneakersnstuff.com/images/314976/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/314977/da8291-001-2.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/314975/da8291-001-1.jpg",
    instock: true,
    description: "Nike Waffle Trainer 2 gives you the original look of Nike Running and celebrates the 50th anniversary of Swoosh. With its classic Waffle sole and retro material that flashes to 70s athletics and its original Swoosh design, it celebrates Nike's humble beginnings.",
  },
  {
    artno: "M990cp2",
    model: "990v2",
    brand: "New Balance",
    price: 175,
    sizes: ["5"],
    colors: ["Grey", "Multi color"],
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/316752/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/316751/02a2531.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/316754/02a2537.jpg",
    instock: true,
    description: "The iconic New Balance Made In US 990v2 has a shock-absorbing ABZORB midsole that provides the support and comfort you need every day. The shoe is made of first-class pigskin and mesh, and gives a timeless style to any outfit.",
  },
  {
    artno: "Q46229",
    model: "4D Futurecraft",
    brand: "adidas Performance",
    price: 219,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: ["crystal white", "chalk white", "core black"],
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/308942/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/308941/product_medium.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/308943/product_medium.jpg",
    instock: true,
  },
  {
    artno: "Da7995-101",
    model: "Waffle One",
    brand: "Nike Sportswear",
    price: 99,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: ["COCONUT MILK", "BRIGHT CRIMSON-HYPER ROYAL"],
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/304586/da7995-101-5.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/304588/product_small.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/304590/product_small.jpg",
    instock: true,
  },
  {
    artno: "Q46439",
    model: "Ultra 4D",
    brand: "adidas Performance",
    price: 219,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: ["collegiate green", "ftwr white", "collegiate orange"],
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/304856/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/304851/product_small.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/304854/product_small.jpg",
    instock: true,
  },
  {
    artno: "Dc5331-001",
    model: "Air Max Pre-Day LX",
    brand: "Nike Sportswear",
    price: 139,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: ["PHANTOM", "BLACK-RATTAN-LIGHT BONE"],
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/303686/product_medium.jpg",
    imgURL2: "",
    imgURL3: "",
    instock: true,
  },
  {
    artno: "374921-15",
    model: "Suede VTG",
    brand: "Puma",
    price: 89,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: ["Dill", "Vaporous Gray", "White"],
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/318646/shoes-puma-1.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/317584/product_xsmall.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/317583/product_xsmall.jpg",
    instock: true,
  },
];
