export const catalog = [
  {
    artno: "Dm7582-100",
    model: "Blazer Low '77 Premium",
    brand: "Nike",
    price: 99,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: "Beige",
    sex: "Men",
    imgURL: "https://www.sneakersnstuff.com/images/314995/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/314994/dm7582-100-2.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/314996/dm7582-100-1.jpg",
    instock: true,
    description: "An unusual combination of materials and a vintage look define the Nike Blazer range. The Nike Blazer's are available as low-top's and high-top's and in a variety of different colourways and patterns.",
  },
  {
    artno: "Da8291-001",
    model: "Wmns Waffle Trainer 2",
    brand: "Nike",
    price: 89,
    sizes: ["5", "5.5", "6", "6.5", "7", "7.5", "8", "8.5", "9", "9.5", "10"],
    colors: "Beige",
    sex: "Women",
    imgURL: "https://www.sneakersnstuff.com/images/314976/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/314977/da8291-001-2.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/314975/da8291-001-1.jpg",
    instock: true,
    description: "Nike Waffle Trainer 2 gives you the original look of Nike Running and celebrates the 50th anniversary of Swoosh. With its classic Waffle sole and retro material that flashes to 70s athletics and its original Swoosh design, it celebrates Nike's humble beginnings.",
  },
  {
    artno: "M990cp2",
    model: "990v2",
    brand: "New Balance",
    price: 175,
    sizes: ["5"],
    colors: "Multi-color",
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/316752/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/316751/02a2531.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/316754/02a2537.jpg",
    instock: true,
    description: "The iconic New Balance Made In US 990v2 has a shock-absorbing ABZORB midsole that provides the support and comfort you need every day. The shoe is made of first-class pigskin and mesh, and gives a timeless style to any outfit.",
  },
  {
    artno: "Q46229",
    model: "4D Futurecraft",
    brand: "adidas Performance",
    price: 219,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: "White",
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/308942/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/308941/product_medium.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/308943/product_medium.jpg",
    instock: true,
    description: "The adidas Futurecraft 4D returns after its original release in 2018. Dressed in Core White, the futuristic cutting-edge adidas sneaker comes with a 4D midsole and a digitally engineered construction, the low-top lightweight adidas shoe comes with a Primeknit upper for a locked-in feel and touch.",
  },
  {
    artno: "Da7995-101",
    model: "Waffle One",
    brand: "Nike Sportswear",
    price: 99,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: "Beige",
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/304586/da7995-101-5.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/304588/product_small.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/304590/product_small.jpg",
    instock: true,
    description: "The Nike Waffle One delivers vibrant colors and the soft materials draw inspiration in the vibes from your favorites among influencers on social media. The speckled shoelaces give the right discreet feel and the right kind of Swoosh style.",
  },
  {
    artno: "Q46439",
    model: "Ultra 4D",
    brand: "adidas Performance",
    price: 219,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: "Green",
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/304856/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/304851/product_small.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/304854/product_small.jpg",
    instock: true,
    description: "When the adidas Ultraboost debuted in 2015, it quickly gained ground far beyond the world of running. With this version, adidas has redesigned their design with a 3D-printed midsole. The denser parts of the grid provide support and the more open parts feel more shock-absorbing. This shoe does not just look like the future. It feels that way too.",
  },
  {
    artno: "Dc5331-001",
    model: "Air Max Pre-Day LX",
    brand: "Nike Sportswear",
    price: 139,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: "Beige",
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/303686/product_medium.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/303691/dc5331-001-6.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/303692/dc5331-001-7.jpg",
    instock: true,
    description: "The Nike Air Max Pre Day LX takes classic details of heritage Nike running into a new realm, this brings you a fast-paced look that's ready for today's world. Made with at least 20% recycled materials by weight, this wardrobe staple combines the retro track aesthetic you know best with a new Air window to help energize the look and feel. The updated rubber Waffle sole adds heritage styling, traction, and durability, inspired by heritage running shoes, the upper features a large retro Swoosh, stitched overlays with throwback looks, and a mix of materials.",
  },
  {
    artno: "374921-15",
    model: "Suede VTG",
    brand: "Puma",
    price: 89,
    sizes: ["7.5", "8", "8.5", "9", "9.5", "10", "11"],
    colors: "Green",
    sex: "Unisex",
    imgURL: "https://www.sneakersnstuff.com/images/318646/shoes-puma-1.jpg",
    imgURL2: "https://www.sneakersnstuff.com/images/317584/product_xsmall.jpg",
    imgURL3: "https://www.sneakersnstuff.com/images/317583/product_xsmall.jpg",
    instock: true,
    description: "You might have seen the Puma Suede a bunch of times, but did it get as close as possible to the original version like this Puma Suede VTG? Introduced in 1968, this rendition comes with a lower panel, like the OG silhouette back in the days. Equipped with a red upper and white overlays, the Puma Suede is finished off by metallic gold branding.",
  },
];
